"""initial revision

Revision ID: 7325cd96f9b7
Revises: 
Create Date: 2022-03-15 11:17:23.266003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7325cd96f9b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('shortname', sa.String(), nullable=True),
    sa.Column('association_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('representative_address', sa.String(), nullable=True),
    sa.Column('representative_plz', sa.Integer(), nullable=True),
    sa.Column('representative_city', sa.String(), nullable=True),
    sa.Column('representative_email', sa.String(), nullable=True),
    sa.Column('it_representative', sa.String(), nullable=True),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('impressum', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_association_association_name'), 'association', ['association_name'], unique=True)
    op.create_index(op.f('ix_association_homepage'), 'association', ['homepage'], unique=False)
    op.create_index(op.f('ix_association_id'), 'association', ['id'], unique=False)
    op.create_index(op.f('ix_association_number'), 'association', ['number'], unique=True)
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.Column('association_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['association_id'], ['association.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_id'), 'problem', ['id'], unique=False)
    op.create_index(op.f('ix_problem_type'), 'problem', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_type'), table_name='problem')
    op.drop_index(op.f('ix_problem_id'), table_name='problem')
    op.drop_table('problem')
    op.drop_index(op.f('ix_association_number'), table_name='association')
    op.drop_index(op.f('ix_association_id'), table_name='association')
    op.drop_index(op.f('ix_association_homepage'), table_name='association')
    op.drop_index(op.f('ix_association_association_name'), table_name='association')
    op.drop_table('association')
    # ### end Alembic commands ###
